# Example Demonstration: Exploring get_distance_matrix, get_substitution_matrix, and clara to Display
*Author: Xinyi Li   Date: March 1, 2025*

**Data Source**: The sample dataset used in this demonstration is sourced from Gapminder, compiling data from 223 countries spanning the years 1800 to 2022. We have extracted data related to CO₂ emissions for distance matrix computation and clustering analysis.<br>

This dataset categorizes CO₂ emission levels into five states: "Very Low" (Below 20%), "Low" (20–40%), "Middle" (40–60%), "High" (60–80%), "Very High" (Top 80%)<br>These categories represent different levels of CO₂ emissions.

In this article, we will use this dataset to demonstrate the functionality and usage of the following functions: *get_distance_matrix*, *get_substitution_matrix*, *clara*.

### Contents:
- Chapter 1: get_distance_matrix
- Chapter 2: get_substitution_matrix
- Chapter 3: clara

Let’s get started!

In [1]:
# Import necessary libraries
from sequenzo import * # Social sequence analysis
import pandas as pd # Import necesarry packages
import numpy as np

In [2]:
# Load the data that we would like to explore in this tutorial
# `df` is the short for `dataframe`, which is a common variable name for a dataset
# df = load_dataset('country_co2_emissions')
df = pd.read_csv('D:/country_co2_emissions_missing.csv')

# show
df

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,...,High,High,High,High,High,High,High,High,High,High
1,Albania,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,...,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High
2,Algeria,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,...,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High
3,Andorra,High,High,High,High,High,High,High,High,High,...,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High,Very High
4,Angola,Low,Low,Low,Low,Low,Low,Low,Low,Low,...,High,High,High,High,High,High,High,High,High,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Venezuela,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,...,Very High,Very High,Very High,Very High,Very High,High,Middle,High,High,High
190,Vietnam,Low,Low,Low,Low,Low,Low,Low,Low,Low,...,High,High,High,High,High,Very High,Very High,Very High,Very High,Very High
191,Yemen,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,Very Low,...,High,High,High,High,High,High,High,High,High,High
192,Zambia,High,High,High,High,High,High,High,High,High,...,High,High,High,High,High,High,High,High,High,High
193,Zimbabwe,Middle,Middle,Middle,Middle,Middle,Middle,Middle,Middle,Middle,...,High,High,High,High,High,High,High,High,High,High

In [7]:
# If it is a multidimensional matrix, 
# wrap the matrix with states to make the output of the matrix more interpretable
def output(data, time, states): # The data consists of two parts: indel and sm
    print("indel: ", data['indel'])
    states.insert(0, "null")
    print("sm:")
    for i in range(data['sm'].shape[0]):
        print(f" , , {time[i]}")
        _df = pd.DataFrame(data['sm'][i, :, :], index=states, columns=states)
        print(_df)

In [3]:
# Ctrate SeqdataData
# Define the time-span variable
time = list(df.columns)[1:]

states = ['Very Low', 'Low', 'Middle', 'High', 'Very High']

sequence_data = SequenceData(df, time=time, time_type="year", id_col="country", states=states)

sequence_data

[>] SequenceData initialized successfully! Here's a summary:
[>] Number of sequences: 194
[>] Min/Max sequence length: 223 / 223
[>] There are 0 sequences with missing values, which are []
[>] Alphabet: ['Very Low', 'Low', 'Middle', 'High', 'Very High', 'Missing', 'Missing', 'Missing']

SequenceData(194 sequences, Alphabet: ['Very Low', 'Low', 'Middle', 'High', 'Very High', 'Missing', 'Missing', 'Missing'])

# Chapter 1: get_distance_matrix
Below are the examples from the *get_distance_matrix* official documentation.

**Note**: The 5th example (DHD) is provided as a **counterexample**—it demonstrates an unsupported computation method. As a result, the function returns an incorrect output.

In [5]:
# refseq
refseq = [[0, 1, 2], [99, 100]] # Reference sequences set

om = get_distance_matrix(sequence_data,
                         method="OM",
                         refseq=refseq,
                         sm="TRATE",
                         indel="auto")
om

[>] Processing 194 sequences with 6 unique states.
[>] Transition-based substitution-cost matrix (TRATE) initiated...
  - Computing transition probabilities for: [Very Low, Low, Middle, High, Very High, Missing]
[>] Indel cost generated.

[>] Pairwise measures between two subsets of sequences of sizes 3 and 2
[>] Identified 5 unique sequences.
[>] Sequence length: min/max = 223 / 223.

[>] Starting Optimal Matching(OM)...
[>] Computed Successfully.

              Lithuania  Luxembourg
Afghanistan  183.953446  341.902297
Albania      196.629013  386.107284
Algeria      126.000000  299.890765

In [6]:
# 1. OMspell + TRATE
omspell = get_distance_matrix(sequence_data,
                         method="OMspell",
                         sm="TRATE",
                         indel="auto")
omspell

[>] Processing 194 sequences with 7 unique states.
[>] Transition-based substitution-cost matrix (TRATE) initiated...
  - Computing transition probabilities for: [null, Very Low, Low, Middle, High, Very High, Missing]
[>] Indel cost generated.

[>] Identified 192 unique spell sequences.
[>] Sequence spell length: min/max = 1 / 24.

[>] Starting Optimal Matching with spell(OMspell)...
[>] Computing all pairwise distances...
[>] Computed Successfully.

,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,Uganda,Ukraine,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
Afghanistan,0.000000,69.447981,69.466725,214.0,183.500000,180.000000,187.500000,107.499418,182.500000,188.499418,...,89.500000,117.500000,151.498799,116.500000,166.466725,91.896885,166.000000,58.499418,213.5,186.843289
Albania,69.447981,0.000000,55.966725,182.5,197.000000,179.500000,180.000000,96.967925,176.000000,165.000000,...,122.000000,102.999418,137.948563,104.999418,176.999418,76.500000,187.484482,58.999418,203.0,168.500000
Algeria,69.466725,55.966725,0.000000,153.5,187.000000,153.500000,144.000000,89.000000,145.000000,152.000000,...,106.000000,76.000000,125.997998,75.000000,190.960807,39.500000,180.483481,68.948563,205.0,195.500000
Andorra,214.000000,182.500000,153.500000,0.0,170.500000,170.000000,52.500000,165.500000,66.500000,132.500000,...,225.448563,117.500000,189.500000,106.500000,159.460807,137.000000,166.000000,171.500000,125.5,190.000000
Angola,183.500000,197.000000,187.000000,170.5,0.000000,135.500000,153.000000,167.000000,170.000000,194.000000,...,155.000000,171.000000,130.948563,170.000000,95.000000,204.500000,59.500000,155.999418,170.0,179.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,91.896885,76.500000,39.500000,137.0,204.500000,162.000000,134.500000,102.500000,129.500000,131.500000,...,112.500000,61.500000,134.500000,62.499418,202.500000,0.000000,199.999418,92.500000,216.5,200.000000
Vietnam,166.000000,187.484482,180.483481,166.0,59.500000,124.999418,140.500000,156.499418,157.500000,175.499418,...,150.500000,163.500000,110.396885,163.500000,76.428732,199.999418,0.000000,146.499418,171.5,163.895926
Yemen,58.499418,58.999418,68.948563,171.5,155.999418,194.500000,171.948563,116.000000,187.967344,201.967925,...,108.948563,127.948563,155.000000,126.948563,152.999418,92.500000,146.499418,0.000000,171.0,184.467925
Zambia,213.500000,203.000000,205.000000,125.5,170.000000,209.500000,124.000000,198.000000,190.000000,210.000000,...,224.948563,198.000000,222.000000,196.000000,159.000000,216.500000,171.500000,171.000000,0.0,195.500000
Zimbabwe,186.843289,168.500000,195.500000,190.0,179.500000,111.000000,139.500000,130.500000,129.500000,133.500000,...,162.500000,160.448563,193.500000,160.448563,130.448563,200.000000,163.895926,184.467925,195.5,0.000000

In [7]:
# 2. OM + CONSTANT
om = get_distance_matrix(sequence_data,
                         method="OM",
                         sm="CONSTANT",
                         indel="auto")
om

[>] Processing 194 sequences with 8 unique states.
  - Creating 9x9 substitution-cost matrix using 2 as constant value
[>] Indel cost generated.

[>] Identified 192 unique sequences.
[>] Sequence length: min/max = 216 / 223.

[>] Starting Optimal Matching(OM)...
[>] Computing all pairwise distances...
[>] Computed Successfully.

,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,Uganda,Ukraine,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
Afghanistan,0.0,130.0,118.0,408.0,354.0,316.0,334.0,182.0,334.0,340.0,...,140.0,226.0,272.0,228.0,316.0,162.0,306.0,110.0,408.0,334.0
Albania,130.0,0.0,88.0,286.0,330.0,350.0,284.0,180.0,322.0,304.0,...,234.0,192.0,266.0,192.0,318.0,138.0,308.0,54.0,326.0,306.0
Algeria,118.0,88.0,0.0,300.0,360.0,264.0,282.0,126.0,282.0,282.0,...,200.0,142.0,194.0,144.0,360.0,68.0,350.0,124.0,402.0,352.0
Andorra,408.0,286.0,300.0,0.0,334.0,294.0,104.0,288.0,124.0,128.0,...,446.0,188.0,324.0,182.0,250.0,264.0,294.0,310.0,250.0,250.0
Angola,354.0,330.0,360.0,334.0,0.0,256.0,300.0,292.0,334.0,318.0,...,304.0,306.0,212.0,306.0,182.0,390.0,104.0,306.0,334.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,162.0,138.0,68.0,264.0,390.0,282.0,260.0,164.0,248.0,246.0,...,216.0,118.0,212.0,120.0,388.0,0.0,388.0,176.0,414.0,366.0
Vietnam,306.0,308.0,350.0,294.0,104.0,184.0,224.0,224.0,262.0,266.0,...,242.0,292.0,198.0,290.0,116.0,388.0,0.0,282.0,304.0,224.0
Yemen,110.0,54.0,124.0,310.0,306.0,378.0,310.0,198.0,370.0,354.0,...,214.0,222.0,292.0,222.0,282.0,176.0,282.0,0.0,310.0,308.0
Zambia,408.0,326.0,402.0,250.0,334.0,406.0,246.0,360.0,370.0,354.0,...,446.0,362.0,410.0,360.0,242.0,414.0,304.0,310.0,0.0,248.0
Zimbabwe,334.0,306.0,352.0,250.0,300.0,198.0,148.0,234.0,222.0,244.0,...,310.0,304.0,346.0,300.0,142.0,366.0,224.0,308.0,248.0,0.0

In [8]:
# 3. HAM + TRATE
ham = get_distance_matrix(sequence_data,
                          method="HAM",
                          sm="TRATE",
                          indel="auto")
ham

[>] Processing 194 sequences with 9 unique states.
[>] Transition-based substitution-cost matrix (TRATE) initiated...
  - Computing transition probabilities for: [null, null, null, Very Low, Low, Middle, High, Very High, Missing]
[>] Indel cost generated.

[>] Identified 192 unique sequences.
[>] Sequence length: min/max = 216 / 223.

[>] Starting (Dynamic) Hamming Distance(DHD/HAM)...
[>] Computing all pairwise distances...
[>] Computed Successfully.

,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,Uganda,Ukraine,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
Afghanistan,0.000000,163.715397,186.363017,445.216586,387.645710,443.941048,445.166313,310.359423,445.161511,445.183599,...,146.053322,325.044898,345.699481,325.061301,402.911112,209.301036,409.893879,117.725731,405.807815,409.940796
Albania,163.715397,0.000000,96.374471,395.635013,375.930348,353.261271,373.864089,202.372780,395.579938,383.736408,...,237.095295,273.502635,268.934419,275.479728,323.948635,175.405306,344.759112,86.924739,324.888153,344.502396
Algeria,186.363017,96.374471,0.000000,343.118210,404.868303,308.048601,342.601182,218.079263,343.063135,342.829846,...,216.382240,222.889887,227.590879,222.957028,398.449326,124.893192,395.967010,149.497771,399.508800,389.965218
Andorra,445.216586,395.635013,343.118210,0.000000,443.664682,327.011439,199.390109,343.497511,124.732541,148.543814,...,445.936207,251.617963,335.206542,249.529697,439.861780,285.355307,432.971293,441.320065,245.100821,405.073239
Angola,387.645710,375.930348,404.868303,443.664682,0.000000,324.243702,442.021243,381.264836,441.748585,442.473063,...,323.344272,422.072086,244.436368,424.102717,216.999262,425.896513,122.291845,314.959248,332.895240,343.444823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,209.301036,175.405306,124.893192,285.355307,425.896513,321.367596,284.898547,187.857517,285.300231,296.984928,...,231.296257,145.206706,247.422288,147.157543,413.348226,0.000000,405.687704,205.404515,410.383540,378.915103
Vietnam,409.893879,344.759112,395.967010,432.971293,122.291845,241.146902,402.143620,285.897714,430.955403,423.690802,...,424.365908,392.369658,291.624536,398.285565,160.648769,405.687704,0.000000,329.511903,301.165971,290.870450
Yemen,117.725731,86.924739,149.497771,441.320065,314.959248,418.627206,441.261368,269.766225,441.264990,441.282024,...,209.962281,321.147535,320.248572,321.164780,310.928145,205.404515,329.511903,0.000000,309.927722,327.486159
Zambia,405.807815,324.888153,399.508800,245.100821,332.895240,399.131918,240.567047,355.595806,361.990136,346.585277,...,442.426815,357.348953,406.908199,355.362397,238.689852,410.383540,301.165971,309.927722,0.000000,241.817747
Zimbabwe,409.940796,344.502396,389.965218,405.073239,343.444823,296.187133,252.233941,314.171701,284.160602,322.507410,...,442.615749,325.638722,403.188734,317.812863,170.843905,378.915103,290.870450,327.486159,241.817747,0.000000

In [9]:
# 4. DHD + CONSTANT
dhd = get_distance_matrix(sequence_data,
                         method="DHD",
                         sm="CONSTANT",
                         indel="auto")
dhd

[>] Processing 194 sequences with 12 unique states.

ValueError: [!] 'sm = "CONSTANT"' is not relevant for DHD, consider HAM instead.

# Chapter 2: get_substitution_matrix
Below are the examples from the *get_substitution_matrix* official documentation.

**Note**: There is a major issue when running code with .ipynb: it retains variables.

Therefore, to ensure that the variables are not affected by the previous get_distance_matrix when testing get_substitution_cost_matrix, please do not run the previous get_distance_matrix. Of course, this is not a problem with the code, but a characteristic of .ipynb.

Also, even for get_subsitution_cost_matrix, you cannot run the following two code blocks in.ipynb unless you are not using.ipynb

In [8]:
# 1. TRATE + time_varying(True)
sm = get_substitution_cost_matrix(sequence_data,
                                  method="TRATE",
                                  cval=4,
                                  time_varying=True)

# sm is an nd.array due to efficiency, 
# but the output is poorly interpretable, 
# so the output function is used
output(sm, time, states)

[>] Transition-based substitution-cost matrix (TRATE) initiated...
  - Computing transition probabilities for: [Very Low, Low, Middle, High, Very High, Missing]
[>] Indel cost generated.

indel:  1
sm:
 , , 1800
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0  4.000000  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0  0.000000  3.979167  4.000000   4.0        4.0      4.0
Low         4.0  3.979167  0.000000  3.941176   4.0        4.0      4.0
Middle      4.0  4.000000  3.941176  0.000000   4.0        4.0      4.0
High        4.0  4.000000  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000  4.000000   4.0        4.0      0.0
 , , 1801
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0  4.000000  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989583  4.000000   4.0        4.0      4.0
Low         4.0  3.989583  0.000000  3.970588   4.0        4.0      4.0
Middle      4.0  4.000000  3.970588  0.000000   4.0        4.0      4.0
High        4.0  4.000000  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000  4.000000   4.0        4.0      0.0
 , , 1802
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0  4.000000  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989474  4.000000   4.0        4.0      4.0
Low         4.0  3.989474  0.000000  3.981818   4.0        4.0      4.0
Middle      4.0  4.000000  3.981818  0.000000   4.0        4.0      4.0
High        4.0  4.000000  4.000000  4.000000   0.0        3.5      4.0
Very High   4.0  4.000000  4.000000  4.000000   3.5        0.0      4.0
Missing     4.0  4.000000  4.000000  4.000000   4.0        4.0      0.0
 , , 1803
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0  4.000000  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989474  4.000000   4.0        4.0      4.0
Low         4.0  3.989474  0.000000  3.963636   4.0        4.0      4.0
Middle      4.0  4.000000  3.963636  0.000000   4.0        4.0      4.0
High        4.0  4.000000  4.000000  4.000000   0.0        3.5      4.0
Very High   4.0  4.000000  4.000000  4.000000   3.5        0.0      4.0
Missing     4.0  4.000000  4.000000  4.000000   4.0        4.0      0.0
 , , 1804
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0  4.000000  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989362  4.000000   4.0        4.0      4.0
Low         4.0  3.989362  0.000000  3.981818   4.0        4.0      4.0
Middle      4.0  4.000000  3.981818  0.000000   4.0        4.0      4.0
High        4.0  4.000000  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000  4.000000   4.0        4.0      0.0
 , , 1805
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989362     4.0   4.0        4.0      4.0
Low         4.0  3.989362  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1806
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989247     4.0   4.0        4.0      4.0
Low         4.0  3.989247  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1807
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989247     4.0   4.0        4.0      4.0
Low         4.0  3.989247  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1808
           null  Very Low  Low  Middle  High  Very High  Missing
null        0.0       4.0  4.0     4.0   4.0        4.0      4.0
Very Low    4.0       0.0  4.0     4.0   4.0        4.0      4.0
Low         4.0       4.0  0.0     4.0   4.0        4.0      4.0
Middle      4.0       4.0  4.0     0.0   4.0        4.0      4.0
High        4.0       4.0  4.0     4.0   0.0        4.0      4.0
Very High   4.0       4.0  4.0     4.0   4.0        0.0      4.0
Missing     4.0       4.0  4.0     4.0   4.0        4.0      0.0
 , , 1809
           null  Very Low  Low    Middle      High  Very High  Missing
null        0.0       4.0  4.0  4.000000  4.000000        4.0      4.0
Very Low    4.0       0.0  4.0  4.000000  4.000000        4.0      4.0
Low         4.0       4.0  0.0  4.000000  4.000000        4.0      4.0
Middle      4.0       4.0  4.0  0.000000  3.971429        4.0      4.0
High        4.0       4.0  4.0  3.971429  0.000000        4.0      4.0
Very High   4.0       4.0  4.0  4.000000  4.000000        0.0      4.0
Missing     4.0       4.0  4.0  4.000000  4.000000        4.0      0.0
 , , 1810
           null  Very Low  Low    Middle      High  Very High  Missing
null        0.0       4.0  4.0  4.000000  4.000000        4.0      4.0
Very Low    4.0       0.0  4.0  4.000000  4.000000        4.0      4.0
Low         4.0       4.0  0.0  4.000000  4.000000        4.0      4.0
Middle      4.0       4.0  4.0  0.000000  3.971429        4.0      4.0
High        4.0       4.0  4.0  3.971429  0.000000        4.0      4.0
Very High   4.0       4.0  4.0  4.000000  4.000000        0.0      4.0
Missing     4.0       4.0  4.0  4.000000  4.000000        4.0      0.0
 , , 1811
           null  Very Low  Low  Middle  High  Very High  Missing
null        0.0       4.0  4.0     4.0   4.0        4.0      4.0
Very Low    4.0       0.0  4.0     4.0   4.0        4.0      4.0
Low         4.0       4.0  0.0     4.0   4.0        4.0      4.0
Middle      4.0       4.0  4.0     0.0   4.0        4.0      4.0
High        4.0       4.0  4.0     4.0   0.0        4.0      4.0
Very High   4.0       4.0  4.0     4.0   4.0        0.0      4.0
Missing     4.0       4.0  4.0     4.0   4.0        4.0      0.0
 , , 1812
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0       4.0  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0       0.0  4.000000  4.000000   4.0        4.0      4.0
Low         4.0       4.0  0.000000  3.970588   4.0        4.0      4.0
Middle      4.0       4.0  3.970588  0.000000   4.0        4.0      4.0
High        4.0       4.0  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0       4.0  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0       4.0  4.000000  4.000000   4.0        4.0      0.0
 , , 1813
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0       4.0  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0       0.0  4.000000  4.000000   4.0        4.0      4.0
Low         4.0       4.0  0.000000  3.922741   4.0        4.0      4.0
Middle      4.0       4.0  3.922741  0.000000   4.0        4.0      4.0
High        4.0       4.0  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0       4.0  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0       4.0  4.000000  4.000000   4.0        4.0      0.0
 , , 1814
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0       4.0  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0       0.0  4.000000  4.000000   4.0        4.0      4.0
Low         4.0       4.0  0.000000  3.934609   4.0        4.0      4.0
Middle      4.0       4.0  3.934609  0.000000   4.0        4.0      4.0
High        4.0       4.0  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0       4.0  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0       4.0  4.000000  4.000000   4.0        4.0      0.0
 , , 1815
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0       4.0  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0       0.0  4.000000  4.000000   4.0        4.0      4.0
Low         4.0       4.0  0.000000  3.982456   4.0        4.0      4.0
Middle      4.0       4.0  3.982456  0.000000   4.0        4.0      4.0
High        4.0       4.0  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0       4.0  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0       4.0  4.000000  4.000000   4.0        4.0      0.0
 , , 1816
           null  Very Low  Low  Middle  High  Very High  Missing
null        0.0       4.0  4.0     4.0   4.0        4.0      4.0
Very Low    4.0       0.0  4.0     4.0   4.0        4.0      4.0
Low         4.0       4.0  0.0     4.0   4.0        4.0      4.0
Middle      4.0       4.0  4.0     0.0   4.0        4.0      4.0
High        4.0       4.0  4.0     4.0   0.0        4.0      4.0
Very High   4.0       4.0  4.0     4.0   4.0        0.0      4.0
Missing     4.0       4.0  4.0     4.0   4.0        4.0      0.0
 , , 1817
           null  Very Low  Low  Middle  High  Very High  Missing
null        0.0       4.0  4.0     4.0   4.0        4.0      4.0
Very Low    4.0       0.0  4.0     4.0   4.0        4.0      4.0
Low         4.0       4.0  0.0     4.0   4.0        4.0      4.0
Middle      4.0       4.0  4.0     0.0   4.0        4.0      4.0
High        4.0       4.0  4.0     4.0   0.0        4.0      4.0
Very High   4.0       4.0  4.0     4.0   4.0        0.0      4.0
Missing     4.0       4.0  4.0     4.0   4.0        4.0      0.0
 , , 1818
           null  Very Low      Low  Middle  High  Very High  Missing
null        0.0   4.00000  4.00000     4.0   4.0        4.0      4.0
Very Low    4.0   0.00000  3.98913     4.0   4.0        4.0      4.0
Low         4.0   3.98913  0.00000     4.0   4.0        4.0      4.0
Middle      4.0   4.00000  4.00000     0.0   4.0        4.0      4.0
High        4.0   4.00000  4.00000     4.0   0.0        4.0      4.0
Very High   4.0   4.00000  4.00000     4.0   4.0        0.0      4.0
Missing     4.0   4.00000  4.00000     4.0   4.0        4.0      0.0
 , , 1819
           null  Very Low      Low  Middle  High  Very High  Missing
null        0.0   4.00000  4.00000     4.0   4.0        4.0      4.0
Very Low    4.0   0.00000  3.98913     4.0   4.0        4.0      4.0
Low         4.0   3.98913  0.00000     4.0   4.0        4.0      4.0
Middle      4.0   4.00000  4.00000     0.0   4.0        4.0      4.0
High        4.0   4.00000  4.00000     4.0   0.0        4.0      4.0
Very High   4.0   4.00000  4.00000     4.0   4.0        0.0      4.0
Missing     4.0   4.00000  4.00000     4.0   4.0        4.0      0.0
 , , 1820
           null  Very Low  Low  Middle  High  Very High  Missing
null        0.0       4.0  4.0     4.0   4.0        4.0      4.0
Very Low    4.0       0.0  4.0     4.0   4.0        4.0      4.0
Low         4.0       4.0  0.0     4.0   4.0        4.0      4.0
Middle      4.0       4.0  4.0     0.0   4.0        4.0      4.0
High        4.0       4.0  4.0     4.0   0.0        4.0      4.0
Very High   4.0       4.0  4.0     4.0   4.0        0.0      4.0
Missing     4.0       4.0  4.0     4.0   4.0        4.0      0.0
 , , 1821
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989011     4.0   4.0        4.0      4.0
Low         4.0  3.989011  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1822
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.989011     4.0   4.0        4.0      4.0
Low         4.0  3.989011  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1823
           null  Very Low  Low  Middle  High  Very High  Missing
null        0.0       4.0  4.0     4.0   4.0        4.0      4.0
Very Low    4.0       0.0  4.0     4.0   4.0        4.0      4.0
Low         4.0       4.0  0.0     4.0   4.0        4.0      4.0
Middle      4.0       4.0  4.0     0.0   4.0        4.0      4.0
High        4.0       4.0  4.0     4.0   0.0        4.0      4.0
Very High   4.0       4.0  4.0     4.0   4.0        0.0      4.0
Missing     4.0       4.0  4.0     4.0   4.0        4.0      0.0
 , , 1824
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.988889     4.0   4.0        4.0      4.0
Low         4.0  3.988889  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1825
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.977653     4.0   4.0        4.0      4.0
Low         4.0  3.977653  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1826
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0  4.000000  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0  0.000000  3.988764  4.000000   4.0        4.0      4.0
Low         4.0  3.988764  0.000000  3.983333   4.0        4.0      4.0
Middle      4.0  4.000000  3.983333  0.000000   4.0        4.0      4.0
High        4.0  4.000000  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000  4.000000   4.0        4.0      0.0
 , , 1827
           null  Very Low       Low    Middle  High  Very High  Missing
null        0.0       4.0  4.000000  4.000000   4.0        4.0      4.0
Very Low    4.0       0.0  4.000000  4.000000   4.0        4.0      4.0
Low         4.0       4.0  0.000000  3.983333   4.0        4.0      4.0
Middle      4.0       4.0  3.983333  0.000000   4.0        4.0      4.0
High        4.0       4.0  4.000000  4.000000   0.0        4.0      4.0
Very High   4.0       4.0  4.000000  4.000000   4.0        0.0      4.0
Missing     4.0       4.0  4.000000  4.000000   4.0        4.0      0.0
 , , 1828
           null  Very Low  Low  Middle  High  Very High  Missing
null        0.0       4.0  4.0     4.0   4.0        4.0      4.0
Very Low    4.0       0.0  4.0     4.0   4.0        4.0      4.0
Low         4.0       4.0  0.0     4.0   4.0        4.0      4.0
Middle      4.0       4.0  4.0     0.0   4.0        4.0      4.0
High        4.0       4.0  4.0     4.0   0.0        4.0      4.0
Very High   4.0       4.0  4.0     4.0   4.0        0.0      4.0
Missing     4.0       4.0  4.0     4.0   4.0        4.0      0.0
 , , 1829
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.983051     4.0   4.0        4.0      4.0
Low         4.0  3.983051  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1830
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.971815     4.0   4.0        4.0      4.0
Low         4.0  3.971815  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1831
           null  Very Low       Low  Middle  High  Very High  Missing
null        0.0  4.000000  4.000000     4.0   4.0        4.0      4.0
Very Low    4.0  0.000000  3.966037     4.0   4.0        4.0      4.0
Low         4.0  3.966037  0.000000     4.0   4.0        4.0      4.0
Middle      4.0  4.000000  4.000000     0.0   4.0        4.0      4.0
High        4.0  4.000000  4.000000     4.0   0.0        4.0      4.0
Very High   4.0  4.000000  4.000000     4.0   4.0        0.0      4.0
Missing     4.0  4.000000  4.000000     4.0   4.0        4.0      0.0
 , , 1832
           null  Very Low       Low    Middle      High  Very High  Missing
null        0.0  4.000000  4.000000  4.000000  4.000000        4.0      4.0
Very Low    4.0  0.000000  3.977273  4.000000  4.000000        4.0      4.0
Low         4.0  3.977273  0.000000  3.983607  4.000000        4.0      4.0
Middle      4.0  4.000000  3.983607  0.000000  3.971429        4.0      4.0
High        4.0  4.000000  4.000000  3.971429  0.000000        4.0      4.0
Very High   4.0  4.000000  4.000000  4.000000  4.000000        0.0      4.0
Missing     4.0  4.000000  4.000000  4.000000  4.000000        4.0      0.0
 , , 1833
           null  Very Low       Low    Middle      High  Very High  Missing
null        0.0       4.0  4.000000  4.000000  4.000000        4.0      4.0
Very Low    4.0       0.0  4.000000  4.000000  4.000000        4.0      4.0
Low         4.0       4.0  0.000000  3.983607  4.000000        4.0      4.0
Middle      4.0       4.0  3.983607  0.000000  3.859524        4.0      4.0
High        4.0       4.0  4.000000  3.859524  0.000000        4.0      4.0
Very High   4.0       4.0  4.000000  4.000000  4.000000        0.0      4.0
Missing     4.0       4.0  4.000000  4.000000  4.000000        4.0      0.0
 , , 1834
           null  Very Low  Low    Middle      High  Very High  Missing
null        0.0       4.0  4.0  4.000000  4.000000        4.0      4.0
Very Low    4.0       0.0  4.0  4.000000  4.000000        4.0      4.0
Low         4.0       4.0  0.0  4.000000  4.000000        4.0      4.0
Middle      4.0       4.0  4.0  0.000000  3.859524        4.0      4.0

In [7]:
# 2. CONSTANT + time_varying(False)
sm = get_substitution_cost_matrix(sequence_data,
                                  method="CONSTANT",
                                  cval=2,
                                  time_varying=False)
sm

  - Creating 7x7 substitution-cost matrix using 2 as constant value
[>] Indel cost generated.

{'indel': 1,
 'sm':            null  Very Low  Low  Middle  High  Very High  Missing
 null        0.0       2.0  2.0     2.0   2.0        2.0      2.0
 Very Low    2.0       0.0  2.0     2.0   2.0        2.0      2.0
 Low         2.0       2.0  0.0     2.0   2.0        2.0      2.0
 Middle      2.0       2.0  2.0     0.0   2.0        2.0      2.0
 High        2.0       2.0  2.0     2.0   0.0        2.0      2.0
 Very High   2.0       2.0  2.0     2.0   2.0        0.0      2.0
 Missing     2.0       2.0  2.0     2.0   2.0        2.0      0.0}

# Chapter 3: clara
Below is the example from the clara official documentation.

In [4]:
# clara
result = clara(sequence_data,
               R=10,
               sample_size=3000,
               kvals=range(2,21),
               criteria=['distance', 'pbm'],
               dist_args={"method": "OMspell", "sm": "TRATE", "indel": "auto"},
               parallel=True,
               stability=True)
result

[>] Starting generalized CLARA for sequence analysis.
[>] Using crisp clustering optimizing the following criterion: distance, pbm.
  - Aggregating 194 sequences...
  - OK (192 unique cases).
[>] Starting iterations...

[>] Aggregating iterations for each k values...

{'param': {'criteria': ['distance', 'pbm'],
  'pam_combine': False,
  'all_criterias': ['distance', 'pbm'],
  'kvals': range(2, 21),
  'method': 'crisp',
  'stability': True},
 'distance': {'kvals': range(2, 21),
  'clara': {0: {'medoids': array([  5, 125], dtype=int64),
    'clustering': array([2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1,
           2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2,
           1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1,
           1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2,
           1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1,
           1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1,
           1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1,
           1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1]),
    'evol_diss': array([100.6375519 , 100.6375519 , 100.6375519 , 100.6375519 ,
           100.6375519 ,  94.12467985,  94.12467985,  94.12467985,
            94.12467985,  91.07168718]),
    'iter_objective': [100.63755189678045,
     116.3890142786277,
     101.85096362507956,
     121.63431993677924,
     105.95909332110763,
     94.12467985312799,
     118.44756120417978,
     103.01124728288016,
     123.66869502939021,
     91.07168717721648],
    'objective': 91.07168717721648,
    'iteration': 9,
    'arimatrix':         ARI        JC
    0  0.460178  0.580037
    1  0.000054  0.336829
    2  0.784947  0.810130
    3 -0.002541  0.441096
    4  0.037548  0.368941
    5  0.518295  0.614286
    6  0.097481  0.397518
    7  0.133267  0.426156
    8  0.183257  0.480427
    9  1.000000  1.000000,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 91.07168717721648,
    'pbm': 0.7910487946776684,
    'db': 1.1132426277709346,
    'xb': 0.5621709085013362,
    'ams': 0.3977864468225377,
    'ari08': 1,
    'jc08': 2,
    'R': 10,
    'k': 0},
   1: {'medoids': array([152,  12,   2], dtype=int64),
    'clustering': array([3, 3, 3, 2, 1, 1, 2, 3, 1, 2, 3, 2, 2, 3, 3, 3, 1, 1, 1, 3, 3, 2,
           3, 1, 2, 3, 3, 3, 3, 1, 1, 2, 1, 3, 2, 3, 3, 1, 3, 1, 1, 1, 2, 3,
           2, 1, 1, 2, 3, 3, 3, 3, 1, 1, 3, 1, 3, 3, 2, 1, 1, 1, 1, 3, 2, 1,
           1, 1, 3, 1, 3, 2, 3, 1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 3, 2, 3,
           2, 3, 2, 3, 3, 3, 3, 2, 1, 1, 2, 3, 1, 3, 1, 2, 3, 3, 2, 1, 1, 2,
           1, 1, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 1, 3, 3, 3, 3, 2, 1, 3, 1, 2,
           1, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 1, 1, 1, 2, 1, 1, 2, 1, 2,
           3, 3, 3, 3, 1, 3, 2, 1, 3, 3, 1, 2, 1, 1, 3, 3, 3, 1, 3, 1, 3, 3,
           1, 3, 1, 3, 1, 3, 1, 1, 3, 3, 1, 3, 1, 3, 1, 3, 2, 2]),
    'evol_diss': array([103.34164559, 103.34164559, 103.31587239, 103.31587239,
           103.31587239,  94.61699581,  94.61699581,  94.61699581,
            94.61699581,  94.61699581]),
    'iter_objective': [103.34164558705699,
     103.34164558705699,
     103.3158723911807,
     103.3158723911807,
     103.431851772624,
     94.61699581157711,
     103.3158723911807,
     103.3158723911807,
     103.3158723911807,
     103.3158723911807],
    'objective': 94.61699581157711,
    'iteration': 5,
    'arimatrix':         ARI        JC
    0  0.120391  0.288105
    1  0.120391  0.288105
    2  0.120391  0.288105
    3  0.120391  0.288105
    4  0.119755  0.288644
    5  1.000000  1.000000
    6  0.120391  0.288105
    7  0.120391  0.288105
    8  0.120391  0.288105
    9  0.120391  0.288105,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 94.61699581157711,
    'pbm': 0.2924394382086011,
    'db': 1.5854001531073605,
    'xb': 0.7630402888030412,
    'ams': 0.3727790962513724,
    'ari08': 1,
    'jc08': 1,
    'R': 10,
    'k': 1},
   2: {'medoids': array([145, 152,  11,  24], dtype=int64),
    'clustering': array([1, 3, 3, 4, 1, 3, 4, 3, 3, 3, 3, 3, 4, 1, 2, 3, 2, 1, 1, 1, 3, 3,
           2, 3, 4, 3, 1, 1, 1, 1, 2, 3, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 3, 2,
           3, 2, 3, 3, 1, 3, 2, 3, 1, 1, 1, 2, 1, 3, 1, 2, 2, 1, 1, 3, 3, 1,
           2, 1, 3, 1, 1, 3, 1, 1, 1, 2, 3, 3, 3, 2, 1, 2, 3, 3, 1, 3, 3, 2,
           3, 1, 4, 3, 1, 2, 3, 3, 1, 3, 4, 3, 3, 3, 1, 3, 2, 1, 3, 1, 1, 3,
           1, 1, 3, 3, 3, 3, 1, 3, 3, 3, 1, 4, 2, 4, 3, 1, 3, 3, 2, 2, 1, 3,
           1, 2, 1, 1, 4, 4, 3, 3, 4, 3, 3, 1, 1, 1, 2, 1, 3, 1, 1, 4, 2, 3,
           1, 1, 2, 3, 1, 3, 3, 3, 1, 1, 1, 4, 2, 2, 3, 3, 3, 1, 3, 1, 1, 3,
           2, 3, 1, 4, 1, 3, 2, 2, 1, 3, 2, 3, 1, 2, 1, 1, 4, 3]),
    'evol_diss': array([90.35723145, 90.35723145, 90.35723145, 90.35723145, 90.35723145,
           90.35723145, 90.35723145, 90.35723145, 90.35723145, 90.35723145]),
    'iter_objective': [90.35723145089244,
     90.35723145089244,
     90.35723145089244,
     90.35723145089244,
     91.85207681171718,
     90.35723145089244,
     90.35723145089244,
     90.35723145089244,
     90.35723145089244,
     90.35723145089244],
    'objective': 90.35723145089244,
    'iteration': 0,
    'arimatrix':         ARI        JC
    0  1.000000  1.000000
    1  1.000000  1.000000
    2  1.000000  1.000000
    3  1.000000  1.000000
    4  0.921145  0.900201
    5  1.000000  1.000000
    6  1.000000  1.000000
    7  1.000000  1.000000
    8  1.000000  1.000000
    9  1.000000  1.000000,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 90.35723145089244,
    'pbm': 0.24118533685094695,
    'db': 1.4159750774217041,
    'xb': 0.8405323855896971,
    'ams': 0.3163093791219869,
    'ari08': 10,
    'jc08': 10,
    'R': 10,
    'k': 2},
   3: {'medoids': array([145, 152,  11,  12, 187], dtype=int64),
    'clustering': array([5, 5, 5, 4, 1, 3, 4, 5, 3, 5, 5, 3, 4, 5, 5, 5, 2, 1, 1, 5, 5, 3,
           5, 3, 4, 5, 5, 5, 1, 1, 5, 3, 1, 5, 3, 5, 5, 1, 5, 1, 3, 1, 3, 5,
           3, 2, 3, 3, 1, 5, 5, 5, 1, 1, 1, 2, 5, 5, 1, 2, 2, 1, 1, 5, 5, 1,
           2, 1, 5, 1, 5, 3, 1, 1, 1, 5, 3, 5, 5, 5, 1, 2, 3, 5, 1, 5, 3, 5,
           3, 1, 4, 5, 5, 5, 5, 3, 1, 3, 4, 5, 3, 5, 1, 3, 5, 5, 3, 1, 1, 3,
           1, 1, 5, 3, 3, 5, 5, 3, 3, 3, 5, 4, 2, 5, 5, 5, 5, 3, 5, 5, 1, 3,
           1, 5, 1, 5, 5, 5, 5, 5, 4, 5, 5, 1, 1, 1, 2, 1, 3, 1, 1, 4, 2, 3,
           1, 1, 5, 5, 1, 5, 3, 3, 5, 1, 1, 4, 2, 5, 5, 5, 5, 1, 5, 1, 5, 3,
           2, 5, 1, 5, 1, 3, 2, 2, 1, 5, 5, 5, 1, 5, 1, 5, 4, 3]),
    'evol_diss': array([86.82094159, 86.82094159, 86.82094159, 86.82094159, 86.82094159,
           71.81146167, 71.81146167, 71.81146167, 71.81146167, 71.81146167]),
    'iter_objective': [86.8209415868509,
     86.8209415868509,
     86.8209415868509,
     86.8209415868509,
     88.11733333942823,
     71.81146167396915,
     86.06074874322243,
     86.8209415868509,
     86.8209415868509,
     86.8209415868509],
    'objective': 71.81146167396915,
    'iteration': 5,
    'arimatrix':         ARI        JC
    0  0.259219  0.303924
    1  0.259219  0.303924
    2  0.259219  0.303924
    3  0.259219  0.303924
    4  0.234007  0.290120
    5  1.000000  1.000000
    6  0.252990  0.303275
    7  0.259219  0.303924
    8  0.259219  0.303924
    9  0.259219  0.303924,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 71.81146167396915,
    'pbm': 0.24438197649083698,
    'db': 1.2652315561149572,
    'xb': 0.6680135969671549,
    'ams': 0.4051465273406337,
    'ari08': 1,
    'jc08': 1,
    'R': 10,
    'k': 3},
   4: {'medoids': array([ 41,  45, 148,  12, 187,  18], dtype=int64),
    'clustering': array([5, 5, 5, 4, 6, 1, 3, 5, 3, 5, 5, 3, 4, 5, 5, 5, 2, 1, 6, 5, 5, 3,
           5, 3, 4, 5, 5, 5, 6, 6, 5, 3, 6, 5, 3, 5, 5, 6, 5, 1, 1, 1, 3, 5,
           3, 2, 3, 3, 1, 5, 5, 5, 1, 6, 1, 2, 5, 5, 1, 2, 2, 6, 6, 5, 5, 1,
           2, 1, 5, 6, 5, 3, 1, 1, 6, 5, 3, 1, 5, 5, 6, 2, 3, 5, 1, 5, 3, 5,
           1, 1, 4, 5, 5, 5, 5, 3, 6, 1, 4, 5, 1, 5, 1, 3, 5, 5, 3, 1, 6, 3,
           1, 1, 5, 3, 3, 5, 5, 3, 3, 3, 5, 4, 2, 5, 5, 5, 5, 3, 5, 5, 6, 3,
           6, 5, 1, 5, 5, 5, 5, 5, 4, 5, 5, 1, 1, 6, 2, 1, 3, 1, 6, 4, 2, 3,
           1, 1, 5, 5, 1, 5, 3, 1, 5, 1, 6, 4, 2, 5, 5, 5, 5, 6, 5, 6, 5, 1,
           2, 5, 1, 5, 1, 3, 2, 2, 1, 5, 6, 5, 1, 5, 1, 5, 4, 3]),
    'evol_diss': array([83.6792273 , 83.6792273 , 71.09476862, 71.09476862, 69.9530565 ,
           69.9530565 , 69.9530565 , 69.9530565 , 69.9530565 , 69.9530565 ]),
    'iter_objective': [83.67922729532023,
     85.95038184715293,
     71.09476861734507,
     85.1127560406907,
     69.95305649785476,
     71.00713975136568,
     85.13337459739172,
     85.95038184715293,
     85.95038184715293,
     85.13337459739172],
    'objective': 69.95305649785476,
    'iteration': 4,
    'arimatrix':         ARI        JC
    0  0.199695  0.247415
    1  0.230667  0.273860
    2  0.842727  0.794900
    3  0.210534  0.258382
    4  1.000000  1.000000
    5  0.841295  0.793203
    6  0.210534  0.258382
    7  0.230667  0.273860
    8  0.230667  0.273860
    9  0.210534  0.258382,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 69.95305649785476,
    'pbm': 0.22366865758418825,
    'db': 1.4167912865559575,
    'xb': 0.9715702291368716,
    'ams': 0.3644181149857746,
    'ari08': 3,
    'jc08': 1,
    'R': 10,
    'k': 4},
   5: {'medoids': array([145, 110, 152,  11,  24,  98,  25], dtype=int64),
    'clustering': array([7, 7, 7, 6, 1, 4, 5, 7, 4, 4, 7, 4, 5, 7, 7, 7, 6, 1, 1, 7, 7, 4,
           7, 4, 5, 7, 7, 7, 7, 1, 3, 4, 1, 7, 4, 7, 7, 1, 7, 1, 4, 1, 4, 7,
           4, 3, 6, 4, 2, 7, 7, 7, 1, 1, 1, 3, 7, 7, 1, 2, 3, 2, 1, 7, 4, 1,
           2, 2, 7, 1, 7, 4, 7, 1, 2, 2, 4, 7, 7, 7, 2, 3, 2, 7, 2, 7, 4, 7,
           4, 1, 6, 7, 7, 7, 7, 4, 1, 2, 6, 7, 2, 7, 1, 4, 7, 7, 4, 2, 1, 4,
           2, 1, 7, 4, 4, 7, 7, 4, 4, 6, 7, 5, 3, 7, 7, 7, 7, 4, 2, 7, 1, 6,
           1, 7, 7, 7, 7, 7, 4, 7, 5, 7, 7, 7, 1, 1, 3, 1, 4, 2, 1, 5, 3, 4,
           1, 7, 7, 7, 1, 7, 4, 4, 7, 2, 1, 5, 2, 2, 7, 7, 7, 1, 7, 1, 7, 4,
           2, 7, 2, 7, 1, 4, 3, 3, 7, 7, 2, 7, 1, 7, 1, 7, 5, 4]),
    'evol_diss': array([62.05358915, 62.05358915, 62.05358915, 62.05358915, 62.05358915,
           62.05358915, 62.05358915, 62.05358915, 62.05358915, 62.05358915]),
    'iter_objective': [62.05358915184644,
     62.66441083459732,
     68.96121879689319,
     83.70554566487966,
     69.31693268039268,
     64.47983225840991,
     64.47983225840991,
     62.66441083459732,
     69.31693268039268,
     63.881897173597174],
    'objective': 62.05358915184644,
    'iteration': 0,
    'arimatrix':         ARI        JC
    0  1.000000  1.000000
    1  0.980054  0.970826
    2  0.691605  0.628102
    3  0.253149  0.278381
    4  0.817610  0.760786
    5  0.800592  0.743233
    6  0.800592  0.743233
    7  0.980054  0.970826
    8  0.817610  0.760786
    9  0.806331  0.748581,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 62.05358915184644,
    'pbm': 0.16698090974027816,
    'db': 1.465408609393947,
    'xb': 1.591117670560165,
    'ams': 0.4189421058770826,
    'ari08': 8,
    'jc08': 3,
    'R': 10,
    'k': 5},
   6: {'medoids': array([132,  65, 152, 167,  11,  24,  98,  25], dtype=int64),
    'clustering': array([8, 8, 8, 7, 1, 2, 6, 8, 5, 4, 8, 5, 6, 8, 8, 8, 7, 2, 1, 8, 8, 5,
           8, 2, 6, 8, 8, 8, 8, 1, 3, 5, 1, 8, 5, 8, 8, 1, 8, 2, 2, 2, 5, 8,
           5, 3, 7, 5, 2, 8, 8, 8, 2, 1, 1, 3, 8, 8, 2, 4, 3, 1, 1, 8, 4, 2,
           4, 2, 8, 1, 8, 5, 8, 2, 1, 4, 5, 8, 8, 8, 1, 3, 2, 8, 2, 8, 5, 8,
           2, 2, 7, 8, 8, 8, 8, 5, 1, 2, 7, 8, 2, 8, 2, 5, 8, 8, 5, 2, 1, 5,
           4, 2, 8, 5, 5, 8, 8, 5, 5, 7, 8, 4, 3, 8, 8, 8, 8, 5, 4, 8, 1, 7,
           1, 8, 2, 8, 8, 8, 4, 8, 6, 8, 8, 2, 2, 1, 3, 1, 5, 2, 1, 6, 3, 5,
           2, 2, 8, 8, 1, 8, 5, 2, 8, 1, 2, 6, 4, 4, 8, 8, 8, 1, 8, 1, 8, 2,
           4, 8, 1, 8, 2, 5, 3, 3, 2, 8, 4, 8, 2, 8, 2, 8, 6, 5]),
    'evol_diss': array([58.98611408, 58.98611408, 58.98611408, 58.98611408, 58.98611408,
           58.98611408, 58.98611408, 58.98611408, 58.98611408, 58.98611408]),
    'iter_objective': [58.98611407581084,
     61.410250748578264,
     65.9558567679032,
     60.9136858067539,
     61.410250748578264,
     61.410250748578264,
     61.38685054199203,
     80.55966540955583,
     61.70602645074571,
     60.779014839423915],
    'objective': 58.98611407581084,
    'iteration': 0,
    'arimatrix':         ARI        JC
    0  1.000000  1.000000
    1  0.714307  0.643610
    2  0.754999  0.684519
    3  0.821380  0.761240
    4  0.714307  0.643610
    5  0.714307  0.643610
    6  0.724282  0.653950
    7  0.255125  0.258630
    8  0.722893  0.652559
    9  0.755610  0.685461,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 58.98611407581084,
    'pbm': 0.14793594557584575,
    'db': 1.4378916997488678,
    'xb': 1.5124644634823292,
    'ams': 0.41524386772030536,
    'ari08': 2,
    'jc08': 1,
    'R': 10,
    'k': 6},
   7: {'medoids': array([132, 110,  65, 152,  11,  12,  98, 162, 187], dtype=int64),
    'clustering': array([8, 8, 8, 7, 1, 3, 6, 8, 5, 9, 9, 5, 6, 8, 8, 9, 7, 3, 1, 8, 8, 5,
           8, 3, 6, 9, 8, 8, 8, 1, 9, 5, 1, 8, 5, 8, 8, 1, 8, 3, 3, 3, 5, 8,
           5, 4, 7, 5, 8, 8, 8, 8, 3, 1, 1, 4, 8, 8, 3, 2, 4, 1, 1, 8, 9, 3,
           2, 3, 8, 1, 8, 5, 8, 3, 1, 2, 5, 8, 8, 8, 2, 4, 2, 9, 2, 9, 5, 9,
           3, 3, 7, 9, 8, 9, 9, 5, 1, 2, 7, 9, 2, 8, 3, 5, 8, 8, 5, 3, 1, 5,
           2, 3, 9, 5, 5, 8, 8, 5, 5, 7, 8, 6, 4, 8, 8, 8, 8, 5, 2, 8, 1, 7,
           1, 8, 8, 8, 8, 8, 9, 9, 6, 9, 9, 8, 8, 1, 4, 1, 5, 2, 1, 6, 4, 5,
           8, 8, 9, 9, 1, 9, 5, 3, 8, 8, 3, 6, 2, 2, 8, 9, 8, 1, 8, 1, 8, 3,
           2, 8, 2, 9, 3, 5, 4, 4, 8, 9, 8, 9, 3, 9, 3, 8, 6, 5]),
    'evol_diss': array([58.18367057, 58.01255943, 58.01255943, 56.33958684, 56.33958684,
           56.33958684, 56.33958684, 56.33958684, 56.33958684, 56.30707018]),
    'iter_objective': [58.18367056899467,
     58.01255942825911,
     58.36591687476993,
     56.33958684154638,
     56.93057413390593,
     56.93057413390593,
     56.9071739273197,
     58.01255942825911,
     57.226349836073375,
     56.30707018351447],
    'objective': 56.30707018351447,
    'iteration': 9,
    'arimatrix':         ARI        JC
    0  0.743905  0.654254
    1  0.610162  0.526667
    2  0.665499  0.572757
    3  0.513302  0.433691
    4  0.935269  0.900647
    5  0.935269  0.900647
    6  0.948332  0.919905
    7  0.610162  0.526667
    8  0.903627  0.855629
    9  1.000000  1.000000,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 56.30707018351447,
    'pbm': 0.12827510509842738,
    'db': 1.4956763308716257,
    'xb': 1.481765004829328,
    'ams': 0.36483701161929544,
    'ari08': 5,
    'jc08': 5,
    'R': 10,
    'k': 7},
   8: {'medoids': array([132, 110,  65, 152,  11, 122,  24,  98,  25, 144], dtype=int64),
    'clustering': array([ 9,  9,  9,  8,  1,  3,  7,  9,  6,  6,  9,  5,  7,  9,  9,  9,  6,
            3,  1,  9,  9,  5, 10,  3,  7,  9, 10, 10, 10,  1,  4,  5,  1, 10,
            5,  9,  9,  1,  9,  3,  3,  3,  5,  9,  5,  4,  6,  5, 10,  9,  9,
            9,  3,  1, 10,  4, 10,  9,  3,  2,  6,  1,  1,  9,  6,  3,  2,  3,
            9,  1, 10,  5, 10,  3,  1,  2,  5, 10,  9,  9,  2,  4,  2,  9,  2,
            9,  5,  9,  3, 10,  8,  9, 10,  9,  9,  5,  1,  2,  8,  9,  2,  9,
            3,  5, 10, 10,  5,  3,  1,  5,  2,  3,  9,  5,  5,  9,  9,  5,  5,
            6,  9,  7,  6,  9,  9, 10,  9,  5,  2,  9,  1,  6,  1, 10, 10, 10,
            9,  9,  6,  9,  7,  9,  9, 10, 10,  1,  4,  1,  5,  2,  1,  7,  4,
            5, 10, 10,  9,  9,  1,  9,  5,  3, 10, 10,  3,  7,  2,  2,  9,  9,
           10,  1,  9,  1, 10,  3,  2,  9,  2,  9,  3,  5,  4,  6, 10,  9,  2,
            9,  3,  9,  3,  9,  7,  5]),
    'evol_diss': array([53.61860637, 53.61860637, 53.61860637, 53.61860637, 53.61860637,
           53.61860637, 53.61860637, 53.61860637, 53.61860637, 53.61860637]),
    'iter_objective': [53.61860636637836,
     54.19077131483197,
     57.062337391310116,
     54.468505779886016,
     57.041923164906656,
     57.047077804081916,
     57.062337391310116,
     54.19077131483197,
     57.32481226913596,
     56.495531412329335],
    'objective': 53.61860636637836,
    'iteration': 0,
    'arimatrix':         ARI        JC
    0  1.000000  1.000000
    1  0.958477  0.934062
    2  0.699838  0.603588
    3  0.923928  0.882448
    4  0.673404  0.576290
    5  0.673404  0.576290
    6  0.699838  0.603588
    7  0.958477  0.934062
    8  0.638718  0.541678
    9  0.718685  0.623830,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 53.61860636637836,
    'pbm': 0.11458353465750647,
    'db': 1.3307787142240468,
    'xb': 1.374836060676368,
    'ams': 0.39341497290561966,
    'ari08': 4,
    'jc08': 4,
    'R': 10,
    'k': 8},
   9: {'medoids': array([132, 110,  65, 152, 157,  11,  46,  12,  98, 144, 187], dtype=int64),
    'clustering': array([ 5,  5,  5,  9,  1,  3,  8, 11,  7,  7, 11,  6,  8,  5,  5, 11,  7,
            3,  1,  5,  5,  6, 10,  3,  8, 11,  5,  5, 10,  1, 11,  6,  1, 10,
            6,  5,  5,  1,  5,  3,  3,  3,  6,  5,  6,  4,  7,  6, 10,  5,  5,
            5,  3,  1, 10,  4, 10,  5,  3,  2,  7,  1,  1, 11, 11,  3,  2,  3,
            5,  1,  5,  6, 10,  3,  1,  2,  6, 10, 10, 11,  2,  4,  2, 11,  2,
           11,  6, 11,  3, 10,  9, 11,  5,  5,  5,  6,  1,  2,  9, 11,  2,  5,
            3,  6, 10,  5,  6,  3,  1,  6,  2,  3, 11,  6,  6,  5,  5,  6,  6,
            7,  5,  8,  7,  5,  5, 10,  5,  6,  2,  5,  1,  7,  1, 10, 10, 10,
            5,  5,  7, 11,  8, 11, 11, 10, 10,  1,  4,  1,  6,  2,  1,  8,  4,
            6, 10, 10, 11,  5,  1, 11,  6,  3, 10, 10,  3,  8,  2,  2,  5,  5,
           10,  1,  5,  1, 10,  3,  2,  5,  2, 11,  3,  6,  4,  7, 10, 11,  2,
           11,  3,  5,  3,  5,  8,  6]),
    'evol_diss': array([52.15184505, 52.15184505, 48.86403892, 48.86403892, 48.86403892,
           48.86403892, 48.86403892, 48.86403892, 48.86403892, 48.29723294]),
    'iter_objective': [52.15184505321028,
     52.63359021956107,
     48.86403891631394,
     52.96525027237883,
     54.05429370686085,
     53.990065047467695,
     53.966664840881464,
     52.63359021956107,
     55.85805918871662,
     48.297232937333156],
    'objective': 48.297232937333156,
    'iteration': 9,
    'arimatrix':         ARI        JC
    0  0.718894  0.619003
    1  0.628001  0.524174
    2  0.977083  0.961954
    3  0.587169  0.485391
    4  0.615982  0.514433
    5  0.613294  0.511847
    6  0.628316  0.526346
    7  0.628001  0.524174
    8  0.580207  0.479234
    9  1.000000  1.000000,
    'criteria': 'distance',
    'method': 'crisp',
    'avg_dist': 48.297232937333156,
    'pbm': 0.14314040613491377,
    'db': 1.26838106766947,
    'xb': 1.270979814140346,
    'ams': 0.424474942847144,
    'ari08': 2,
    'jc08': 2,
    'R': 10,
    'k': 9},
   10: {'medoids': array([132, 110,  65, 152, 157,  11,  46,  12,  98, 143, 144, 187],
          dtype=int64),
    'clustering': array([ 5,  5,  5,  9,  1,  3,  8, 12,  7,  7, 12,  6,  8,  5,  5, 12,  7,
            3,  1,  5,  5,  6, 10,  3,  8, 12,  5, 10, 11,  1, 12,  6,  1, 10,
            6,  5,  5,  1, 10,  3,  3,  3,  6,  5,  6,  4,  7,  6, 11,  5,  5,
            5,  3,  1, 11,  4, 11, 10,  3,  2,  7,  1,  1, 12, 12,  3,  2,  3,
            5,  1, 10,  6, 10,  3,  1,  2,  6, 11, 11, 12,  2,  4,  2, 12,  2,
           12,  6, 12,  3, 11,  9, 12, 10,  5,  5,  6,  1,  2,  9, 12,  2,  5,
            3,  6, 10, 10,  6,  3,  1,  6,  2,  3, 12,  6,  6,  5,  5,  6,  6,
            7,  5,  8,  7,  5, 10, 11,  5,  6,  2,  5,  1,  7,  1, 10, 11, 11,
            5,  5,  7, 12,  8, 12, 12, 10, 11,  1,  4,  1,  6,  2,  1,  8,  4,
            6, 11, 10, 12,  5,  1, 12,  6,  3, 11, 11,  3,  8,  2,  2,  5,  5,
           11,  1,  5,  1, 10,  3,  2,  5,  2, 12,  3,  6,  4,  7, 10, 12,  2,
           12,  3,  5,  3,  5,  8,  6]),

In [25]:
print("Thank you for learning sequence analysis with Sequenzo! ")
print("We hope you found this tutorial insightful.")
print("\n💡 Stay Curious, keep coding, and discover new insights.")
print("✉️ If you have any questions, please feel free to reach out :)")

Thank you for learning sequence analysis with Sequenzo!
We hope you found this tutorial insightful.

💡 Stay Curious, keep coding, and discover new insights.
✉️ If you have any questions, please feel free to reach out :)